test_suites:
    - name: lint
      script_path: /root/okta/okta-oidc-middleware/scripts
      sort_order: '1'
      timeout: '60'
      script_name: lint
      criteria: MERGE
      queue_name: small
    - name: unit
      script_path: /root/okta/okta-oidc-middleware/scripts
      sort_order: '2'
      timeout: '10'
      script_name: unit
      criteria: MERGE
      # a different container type is required to run node20
      queue_name: ci-queue-productionJenga-AL2023
    - name: e2e
      script_path: /root/okta/okta-oidc-middleware/scripts
      sort_order: '3'
      timeout: '10'
      script_name: e2e
      criteria: MERGE
      queue_name: small
    - name: e2e-20
      script_path: /root/okta/okta-oidc-middleware/scripts
      sort_order: '3'
      timeout: '10'
      script_name: e2e
      criteria: MERGE
      # a different container type is required to run node20
      queue_name: ci-queue-productionJenga-AL2023
      script_env:
        NODE_VER: '20.5.0'
    - name: publish
      script_path: /root/okta/okta-oidc-middleware/scripts
      sort_order: '4'
      timeout: '60'
      script_name: publish
      criteria: MERGE
      queue_name: small
    - name: semgrep
      script_path: /root/okta/okta-oidc-middleware/scripts
      sort_order: '5'
      timeout: '10'
      script_name: semgrep
      criteria: MERGE
      queue_name: small