test_suites:
    - name: lint
      script_path: /root/okta/okta-oidc-middleware/scripts
      sort_order: '1'
      timeout: '60'
      script_name: lint
      criteria: MERGE
      queue_name: small
    - name: unit
      script_path: /root/okta/okta-oidc-middleware/scripts
      sort_order: '2'
      timeout: '10'
      script_name: unit
      criteria: MERGE
      # a different container type is required to run node20
      queue_name: ci-queue-productionJenga-AL2023
    - name: e2e
      script_path: /root/okta/okta-oidc-middleware/scripts
      sort_order: '3'
      timeout: '10'
      script_name: e2e
      criteria: MERGE
      queue_name: small
    - name: publish
      script_path: /root/okta/okta-oidc-middleware/scripts
      sort_order: '4'
      timeout: '60'
      script_name: publish
      criteria: MERGE
      queue_name: small
    - name: semgrep
      script_path: /root/okta/okta-oidc-middleware/scripts
      sort_order: '5'
      timeout: '10'
      script_name: semgrep
      criteria: MERGE
      queue_name: small
    - name: e2e-20
      script_path: /root/okta/okta-oidc-middleware/scripts
      sort_order: '6'
      timeout: '15'
      criteria: MERGE
      # a different container type is required to run node20
      queue_name: ci-queue-productionJenga-AL2023
      steps:
        - event: COMMAND
          name: Set Node Version
          action: export NODE_VERSION=20
        - event: COMMAND
          name: E2E Tests
          action: /root/okta/okta-oidc-middleware/scripts/e2e.sh